### ISSUE TITLE
REQUEST - Customer Name Field

### ISSUE THREAD

**Issue by arnydo** [sophos/Sophos-Central-SIEM-Integration#14] opened 2017-11-21 19:59 UTC
Instead of having just the customer id field it would be nice to have the actual customer name come over.
This would help with separating multiple entities when using a SIEM to collect data from multiple customers.

**Comment by taycom** [comment] 2020-05-17 22:37
Hi, any updated about this requirement !!! Please is very important for implantate with differents customers in one SIEM plattform.

**Comment by rkamat** [comment] 2021-09-07 20:34
Duplicate of https://github.com/sophos/Sophos-Central-SIEM-Integration/issues/38

**Closed by rkamat** 2021-09-07 20:34 UTC
